"""Generated by schema/compiler.py -- DO NOT HAND-EDIT. Registers this scene as a Gym env,
same convention as every hand-authored scenes/exp*/__init__.py -- see scenes/__init__.py.
"""

import gymnasium as gym

from . import dual_arm_handoff_env_cfg

gym.register(
    id="Matterix-Experiment-Dual-Arm-Handoff-Generated-v1",
    entry_point="matterix.envs:MatterixBaseEnv",
    kwargs={"env_cfg_entry_point": dual_arm_handoff_env_cfg.DualArmHandoffEnvCfg},
    disable_env_checker=True,
)
