"""Generated by schema/compiler.py from scene_specs/dual_arm_handoff.yaml -- DO NOT HAND-EDIT.
Regenerate with:
    python -m user.matterix_bridge.schema.compile_scene scene_specs/dual_arm_handoff.yaml
"""

from matterix.envs import MatterixBaseEnvCfg, mdp
from matterix.managers import EventManagerCfg
from matterix_assets.equipment import IKA_PLATE_INST_CFG
from matterix_assets.infrastructure import TABLE_SEATTLE_INST_Cfg
from matterix_assets.labware import BEAKER_500ML_INST_CFG
from matterix_assets.robots import FRANKA_PANDA_HIGH_PD_IK_CFG
from user.matterix_bridge.scenes.common import robot_obs_terms
from matterix_sm import PickObjectCfg
from matterix_sm import PlaceObjectCfg
from matterix_sm import WaitCfg
from matterix_sm.robot_action_spaces import FRANKA_IK_ACTION_SPACE

import isaaclab.envs.mdp as isaaclab_mdp
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.utils import configclass

_ROBOT_PICK_BEAKER_KWARGS = dict(description='robot picks up the beaker from the table', agent_assets='robot', object='beaker', action_space_info=FRANKA_IK_ACTION_SPACE)
_ROBOT_PLACE_ON_STATION_KWARGS = dict(description='robot places the beaker on the shared station', agent_assets='robot', target='station', action_space_info=FRANKA_IK_ACTION_SPACE)
_WAIT_FOR_HANDOFF_KWARGS = dict(duration=1.0)
_ROBOT2_PICK_BEAKER_KWARGS = dict(description='robot2 picks up the beaker from the station', agent_assets='robot2', object='beaker', action_space_info=FRANKA_IK_ACTION_SPACE)


@configclass
class EventCfg(EventManagerCfg):
    reset_scene_to_default = EventTerm(func=isaaclab_mdp.reset_scene_to_default, mode="reset")
    randomize_beaker_position = EventTerm(
        func=isaaclab_mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {"x": (-0.05, 0.05), "y": (-0.05, 0.05), "z": (0.0, 0.0)},
            "velocity_range": {},
            "asset_cfg": SceneEntityCfg("beaker"),
        },
    )


@configclass
class ObservationManagerCfg:
    @configclass
    class RigidObjectsGroup(ObsGroup):
        beaker__object_world_pos = ObsTerm(func=mdp.object_world_pos, params={"asset_name": "beaker"})
        beaker__object_world_quat = ObsTerm(func=mdp.object_world_quat, params={"asset_name": "beaker"})
        beaker__pre_grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "pre_grasp"}
        )
        beaker__grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "grasp"}
        )
        beaker__post_grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "post_grasp"}
        )
        station__pre_place_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "station", "frame_name": "pre_place"}
        )
        station__place_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "station", "frame_name": "place"}
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    @configclass
    class ArticulationsGroup(ObsGroup):
        locals().update(robot_obs_terms("robot", FRANKA_IK_ACTION_SPACE))
        locals().update(robot_obs_terms("robot2", FRANKA_IK_ACTION_SPACE))

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    rigid_objects: RigidObjectsGroup = RigidObjectsGroup()
    articulations: ArticulationsGroup = ArticulationsGroup()


@configclass
class DualArmHandoffEnvCfg(MatterixBaseEnvCfg):
    env_spacing = 10.0
    episode_length_s = 60.0
    gripper_joint_names = ['panda_finger_joint1', 'panda_finger_joint2']

    objects = {
        "beaker": BEAKER_500ML_INST_CFG(pos=(0.6, 0.05, 0.05)),
        "table": TABLE_SEATTLE_INST_Cfg(pos=(0.5, 0.0, 0.0)),
        "station": IKA_PLATE_INST_CFG(pos=(0.5, 0.4, 0.12), rot=(0.0, 0.0, 0.0, 1.0)),
    }

    articulated_assets = {
        "robot": FRANKA_PANDA_HIGH_PD_IK_CFG(pos=(0.0, 0.0, 0.0)),
        "robot2": FRANKA_PANDA_HIGH_PD_IK_CFG(pos=(0.0, 0.8, 0.0)),
    }

    observations = ObservationManagerCfg()
    events = EventCfg()

    workflows = {
        "robot_pick_beaker": PickObjectCfg(**_ROBOT_PICK_BEAKER_KWARGS),
        "robot_place_on_station": PlaceObjectCfg(**_ROBOT_PLACE_ON_STATION_KWARGS),
        "wait_for_handoff": WaitCfg(**_WAIT_FOR_HANDOFF_KWARGS),
        "robot2_pick_beaker": PickObjectCfg(**_ROBOT2_PICK_BEAKER_KWARGS),
        "handoff": [
            PickObjectCfg(**_ROBOT_PICK_BEAKER_KWARGS),
            PlaceObjectCfg(**_ROBOT_PLACE_ON_STATION_KWARGS),
            WaitCfg(**_WAIT_FOR_HANDOFF_KWARGS),
            PickObjectCfg(**_ROBOT2_PICK_BEAKER_KWARGS),
        ],
    }
