"""Generated by schema/compiler.py from scene_specs/heater_transfer_generated.yaml -- DO NOT HAND-EDIT.
Regenerate with:
    python -m user.matterix_bridge.schema.compile_scene scene_specs/heater_transfer_generated.yaml
"""

from matterix.envs import MatterixBaseEnvCfg, mdp
from matterix.managers import EventManagerCfg
from matterix.managers.semantics.primitive_semantics.heat_transfer.heat_convection import AmbientAirHeatConvectionCfg
from matterix.managers.semantics.primitive_semantics.is_in_contact import IsInContactPhysicsCfg
from matterix.managers.semantics.semantic_presets.heat_transfer import HeatTransferCfg
from matterix.managers.semantics.semantic_presets.heater import HeaterCfg
from matterix_assets.equipment import IKA_PLATE_INST_CFG
from matterix_assets.infrastructure import TABLE_SEATTLE_INST_Cfg
from matterix_assets.labware import BEAKER_500ML_INST_CFG
from matterix_assets.robots import FRANKA_PANDA_HIGH_PD_IK_CFG
from user.matterix_bridge.scenes.common import robot_obs_terms
from matterix_sm import PickObjectCfg
from matterix_sm import PlaceObjectCfg
from matterix_sm import TurnOnHeaterCfg
from matterix_sm import WaitCfg
from matterix_sm.robot_action_spaces import FRANKA_IK_ACTION_SPACE

import isaaclab.envs.mdp as isaaclab_mdp
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.utils import configclass

_TURN_ON_HEATER_KWARGS = dict(asset_name='ika_plate', value=True, target_temperature=373.15)
_PICK_BEAKER_KWARGS = dict(description='Pick up the beaker', agent_assets='robot', object='beaker', action_space_info=FRANKA_IK_ACTION_SPACE)
_PLACE_BEAKER_KWARGS = dict(description='Place the beaker on top of the IKA plate', agent_assets='robot', target='ika_plate', action_space_info=FRANKA_IK_ACTION_SPACE)
_WAIT_FOR_HEAT_TRANSFER_KWARGS = dict(duration=10.0)
_TURN_OFF_HEATER_KWARGS = dict(asset_name='ika_plate', value=False)


@configclass
class EventCfg(EventManagerCfg):
    reset_scene_to_default = EventTerm(func=isaaclab_mdp.reset_scene_to_default, mode="reset")
    randomize_beaker_position = EventTerm(
        func=isaaclab_mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {"x": (-0.1, 0.1), "y": (-0.1, 0.1), "z": (0.0, 0.0)},
            "velocity_range": {},
            "asset_cfg": SceneEntityCfg("beaker"),
        },
    )
    randomize_beaker_temperature = EventTerm(
        func=mdp.randomize_temperature,
        mode="reset",
        params={"asset_name": "beaker", "min_temp": 293.15, "max_temp": 323.15},
    )


@configclass
class ObservationManagerCfg:
    @configclass
    class PolicyCfg(ObsGroup):
        ee_pos_robot = ObsTerm(func=mdp.ee_env_pos, params={"asset_name": "robot"})
        robot_temperature = ObsTerm(func=mdp.object_temperature, params={"asset_name": "robot"})
        beaker_temperature = ObsTerm(func=mdp.object_temperature, params={"asset_name": "beaker"})
        beaker_is_in_contact = ObsTerm(func=mdp.object_is_in_contact, params={"asset_name": "beaker"})
        ika_plate_temperature = ObsTerm(func=mdp.object_temperature, params={"asset_name": "ika_plate"})
        ika_plate_is_heater_on = ObsTerm(func=mdp.object_is_heater_on, params={"asset_name": "ika_plate"})
        table_temperature = ObsTerm(func=mdp.object_temperature, params={"asset_name": "table"})

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    @configclass
    class RigidObjectsGroup(ObsGroup):
        beaker__object_world_pos = ObsTerm(func=mdp.object_world_pos, params={"asset_name": "beaker"})
        beaker__object_world_quat = ObsTerm(func=mdp.object_world_quat, params={"asset_name": "beaker"})
        beaker__pre_grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "pre_grasp"}
        )
        beaker__grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "grasp"}
        )
        beaker__post_grasp_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "beaker", "frame_name": "post_grasp"}
        )
        ika_plate__pre_place_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "ika_plate", "frame_name": "pre_place"}
        )
        ika_plate__place_frame = ObsTerm(
            func=mdp.frame_world_pose, params={"asset_name": "ika_plate", "frame_name": "place"}
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    @configclass
    class ArticulationsGroup(ObsGroup):
        locals().update(robot_obs_terms("robot", FRANKA_IK_ACTION_SPACE))

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    policy: PolicyCfg = PolicyCfg()
    rigid_objects: RigidObjectsGroup = RigidObjectsGroup()
    articulations: ArticulationsGroup = ArticulationsGroup()


@configclass
class HeaterTransferGeneratedEnvCfg(MatterixBaseEnvCfg):
    env_spacing = 5.0
    episode_length_s = 100.0
    gripper_joint_names = ['panda_finger_joint1', 'panda_finger_joint2']

    objects = {
        "beaker": BEAKER_500ML_INST_CFG(pos=(0.6, 0.05, 0.05), semantics=[IsInContactPhysicsCfg(filter_prim_paths_expr=['ika_plate'], verbose=True), HeatTransferCfg(temp=298.15, C=7920.0, A=0.1, K=200, verbose=True)]),
        "ika_plate": IKA_PLATE_INST_CFG(pos=(0.4, -0.3, 0.12), rot=(0.0, 0.0, 0.0, 1.0), semantics=HeaterCfg(temp=350.15, C=7920.0, A=0.5, heater_on=False, target_temperature=298.15, K_heater=0.1, verbose=True)),
        "table": TABLE_SEATTLE_INST_Cfg(pos=(0.5, 0.0, 0.0), mass=50.0, semantics=HeatTransferCfg(temp=323.15, C=7920.0, A=1.1, verbose=True)),
    }

    articulated_assets = {
        "robot": FRANKA_PANDA_HIGH_PD_IK_CFG(pos=(0.0, 0.0, 0.0), mass=20.0, semantics=HeatTransferCfg(temp=350.15, C=7920.0, A=0.5, verbose=True)),
    }

    observations = ObservationManagerCfg()
    events = EventCfg()

    semantics = [AmbientAirHeatConvectionCfg(verbose=True)]

    workflows = {
        "turn_on_heater": TurnOnHeaterCfg(**_TURN_ON_HEATER_KWARGS),
        "pick_beaker": PickObjectCfg(**_PICK_BEAKER_KWARGS),
        "place_beaker": PlaceObjectCfg(**_PLACE_BEAKER_KWARGS),
        "wait_for_heat_transfer": WaitCfg(**_WAIT_FOR_HEAT_TRANSFER_KWARGS),
        "turn_off_heater": TurnOnHeaterCfg(**_TURN_OFF_HEATER_KWARGS),
        "observe_heating": [
            PickObjectCfg(description='Pick up the (pre-heated) beaker and hold it - watch its temperature rise', agent_assets='robot', object='beaker', action_space_info=FRANKA_IK_ACTION_SPACE),
            WaitCfg(duration=5.0),
        ],
        "pickup_and_place": [
            WaitCfg(duration=2.0),
            TurnOnHeaterCfg(**_TURN_ON_HEATER_KWARGS),
            PickObjectCfg(**_PICK_BEAKER_KWARGS),
            PlaceObjectCfg(**_PLACE_BEAKER_KWARGS),
            WaitCfg(**_WAIT_FOR_HEAT_TRANSFER_KWARGS),
            TurnOnHeaterCfg(**_TURN_OFF_HEATER_KWARGS),
            WaitCfg(duration=5.0),
        ],
    }
