"""Loads catalog.json (see dump_catalog.py at the repo root) and exposes it as a plain,
read-only lookup object.

Deliberately dumb: this module does no validation of its own and doesn't know anything
about scene schemas -- it just gets catalog.json's four top-level dicts (assets, actions,
semantic_presets, primitive_semantics) into a shape models.py's validators can query by
name without repeating `data["assets"]` everywhere. If catalog.json is missing or stale,
that's dump_catalog.py's problem to fix (re-run it), not something this module works
around.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_DEFAULT_CATALOG_PATH = Path(__file__).resolve().parent.parent / "catalog.json"


@dataclass(frozen=True)
class Catalog:
    assets: dict
    actions: dict
    semantic_presets: dict
    primitive_semantics: dict
    generated_at: str


class CatalogNotFoundError(FileNotFoundError):
    pass


@lru_cache(maxsize=8)
def load_catalog(path: str | None = None) -> Catalog:
    """Load catalog.json from `path` (default: catalog.json at the repo root).

    Cached by path (a scene compile run loads this many times across many validators;
    re-parsing the same JSON file on every call would be silent, needless overhead) --
    safe because catalog.json is a build artifact regenerated by a separate offline step
    (dump_catalog.py), never mutated by this process.
    """
    p = Path(path) if path is not None else _DEFAULT_CATALOG_PATH
    if not p.is_file():
        raise CatalogNotFoundError(
            f"{p} not found. Generate it first: EOS_PATH=<eos repo> "
            "<eos-isaaclab python> dump_catalog.py (see CLAUDE.md)."
        )
    with open(p) as f:
        data = json.load(f)
    return Catalog(
        assets=data["assets"],
        actions=data["actions"],
        semantic_presets=data["semantic_presets"],
        primitive_semantics=data["primitive_semantics"],
        generated_at=data["generated_at"],
    )
